### ISSUE TITLE
Request metrics question

### ISSUE THREAD

**Issue by lilaja** [freight-hub/verdaccio-openmetrics#4]
https://github.com/freight-hub/verdaccio-openmetrics/blob/2a6e18caed65826aea1e1da14af26cc38a294cec/src/metrics/requestMetrics.ts#L28

@danopia are you sure this will be called before all other middlewares ( build in verdaccio ) ?
last time i checked it wasn't.

I mean if we start timers at the end of request processing will latencies be accurate?

**Comment by danopia** [comment]
The plugin is apparently placed *after* some built-in middlewares (CORS, etc) and *before* the built-in APIs.

I've previously mentioned this on the other thread @ https://github.com/verdaccio/verdaccio/issues/1815#issuecomment-759702415:

>I've found that middlewares are in front of the internal API in the express stack so the API requests (PUTs, etc) do show up. It seems possible to hack the express handler stack from within the plugin to put the metrics first in 4.x however I haven't seen that as super necessary so I haven't implemented that (meaning things like CORS requests are currently not reported).

So, if one wanted to make the timing metrics more accurate it could make sense to do that handler stack splicing to reorder our handler to the front of the line.

There's also the promise of "next major I was planning to add some sort of lifecycle so some actions can be triggered before and after" which would make it a bit cleaner; not sure if/when we'd see that from upstream though.

**Comment by lilaja** [comment]
Oh sorry i missed that comment, your comment on the original issue. 
Ok that make sense. Thanks!

**Comment by danopia** [comment]
No worries. If for your usecase you want the 'most accurate' possible picture of request time, feel free to make a PR to do the splicing hack; something like:

```js
// register middleware first, then:
const observer = app._router.stack.pop();
app._router.splice(0, 0, observer);
```

In our usecase here, we mostly want to know that package gets/puts are being processed reasonably well & the default stack order has been working well enough for us since most request time is spent within the API routes.
